---
- name: Create monitoring user
  user:
    name: bbb-exporter
    shell: /usr/sbin/nologin
    home: "{{ bbb_monitoring_systemd_directory }}"
    create_home: false
    system: true

- name: Deploy git repository to host
  git:
    repo: https://github.com/greenstatic/bigbluebutton-exporter.git
    dest: "{{ bbb_monitoring_systemd_directory }}"
    version: "{{ bbb_monitoring_exporter_version }}"
  notify:
    - Restart monitoring service

- name: Ensure pip is installed
  apt:
    name:
      - python3-pip
      - python3-setuptools
    state: "{{ bbb_state }}"

- name: Install specified python requirements and custom Index URL
  pip:
    requirements: "{{ bbb_monitoring_systemd_directory }}/requirements.txt"
  notify:
    - Restart monitoring service

- name: Copy systemd service into place
  copy:
    src: "{{ bbb_monitoring_systemd_directory }}/extras/systemd/bigbluebutton-exporter.service"
    dest: /lib/systemd/system/
    owner: root
    group: root
    mode: "0644"
    remote_src: true
  notify:
    - Reload systemd
    - Restart monitoring service

- name: Create /etc/bigbluebutton-exporter directory
  file:
    path: /etc/bigbluebutton-exporter
    state: directory
    mode: "0755"

- name: Template exporter configuration
  template:
    src: monitoring/bbb_exporter_secrets.env.j2
    dest: /etc/bigbluebutton-exporter/settings.env
    mode: "0644"
  notify:
    - Restart monitoring service

- name: Start monitoring
  systemd:
    name: bigbluebutton-exporter
    state: started
    enabled: true
