---
- name: Install socat package
  apt:
    name: socat
    state: "{{ bbb_state }}"

- name: Clone acme into configured directory.
  git:
    repo: "{{ bbb_letsencrypt_repo }}"
    dest: "{{ bbb_letsencrypt_dir }}"
    version: "{{ bbb_letsencrypt_version }}"
    update: "{{ bbb_letsencrypt_keep_updated }}"
    force: true

- name: Set acme.sh script variable.
  set_fact:
    bbb_letsencrypt_script: "{{ bbb_letsencrypt_dir }}/acme.sh"

- name: Ensure acme.sh is executable.
  file:
    path: "{{ bbb_letsencrypt_script }}"
    mode: 0755

- name: acme install
  become: true
  command: "{{ bbb_letsencrypt_install_command }}"
  args:
    chdir: "{{ bbb_letsencrypt_dir }}"
  register: acme_install_result
  changed_when: "'ok' in acme_install_result.stdout"

- name: Generate or renew certificate with acme.sh
  become: true
  command: "{{ bbb_letsencrypt_create_command }}"
  environment:
     email: "{{ bbb_letsencrypt_email }}"
  register: result
  changed_when: "'new certificate deployed' in result.stdout"
  notify: reload nginx
