---
- name: create greenlight directory
  file:
    path: /root/greenlight
    state: directory
    mode: '0644'

- name: register bbb secret
  command: bbb-conf --secret
  changed_when: false
  register: result
  when: not bbb_secret is defined

- name: parse bbb secret
  set_fact:
    bbb_secret: "{{ result.stdout | regex_search('Secret: ([a-zA-Z0-9]*)', multiline=True) |  regex_replace('Secret: ') }}"
    cacheable: true
  when: not bbb_secret is defined

- name: copy greenlight config file
  template:
    src: greenlight/env.j2
    dest: /root/greenlight/.env
    mode: '0644'

- name: copy greenlight docker compose file
  template:
    src: greenlight/docker-compose.yml.j2
    dest: /root/greenlight/docker-compose.yml
    mode: '0644'

- name: copy greenlight nginx configuration file
  template:
    src: "greenlight/{{ item }}.j2"
    dest: "/etc/bigbluebutton/nginx/{{ item }}"
    mode: '0644'
  with_items:
  - greenlight.nginx
  - greenlight-redirect.nginx
  notify: reload nginx

- block:
    - name: start greenlight
      docker_compose:
        pull: true
        project_src: /root/greenlight/

    # https://docs.bigbluebutton.org/greenlight/gl-admin.html#creating-accounts
    - name: Create greenlight users
      command: "docker exec greenlight-v2 bundle exec rake user:create[\"{{ item.name }}\",\"{{ item.email }}\",\"{{ item.password }}\",\"{{ item.type }}\"]"
      loop: "{{ bbb_greenlight_users | flatten(levels=1) }}"
      register: usercreate
      failed_when: "'Invalid Arguments' in usercreate.stdout or 'FATAL' in usercreate.stderr"
      changed_when: "'Account with that email already exists' not in usercreate.stdout"

  when: bbb_greenlight_enable | bool
