---
- name: ensure .rnd exists
  become: true
  copy:
    content: ""
    dest: /root/.rnd
    force: yes
    group: root
    owner: root

- name: generate DTLS-SRTP certificate for kurento
  become: true
  shell:
    cmd: 'umask 137 && openssl req -x509 -new -nodes -newkey rsa:4096 -sha256 -days 3650 -subj "/C=BR/ST=Ottawa/O=BigBlueButton Inc./OU=Live/CN={{ inventory_hostname }}" -keyout /tmp/dtls-srtp-key.pem -out /tmp/dtls-srtp-cert.pem && cat /tmp/dtls-srtp-key.pem /tmp/dtls-srtp-cert.pem > /etc/kurento/dtls-srtp.pem && chgrp kurento /etc/kurento/dtls-srtp.pem && rm /tmp/dtls-srtp-key.pem /tmp/dtls-srtp-cert.pem'
    creates: /etc/kurento/dtls-srtp.pem

- name: use DTLS-SRTP for kurento
  become: true
  lineinfile:
    path: /etc/kurento/modules/kurento/WebRtcEndpoint.conf.ini
    regexp: 'pemCertificateRSA='
    line: 'pemCertificateRSA=/etc/kurento/dtls-srtp.pem'

- name: use DTLS-SRTP for freeswitch
  become: true
  copy:
    remote_src: True
    src: /etc/kurento/dtls-srtp.pem
    dest: /opt/freeswitch/etc/freeswitch/tls/dtls-srtp.pem
    group: daemon
    mode: 0640
  notify: restart freeswitch

- name: add kurento-media-server@.service
  become: true
  template:
    src: kurento-media-server@.service
    dest: "/usr/lib/systemd/system/kurento-media-server-{{ item }}.service"
    mode: 0644
  loop: [ 8888, 8889, 8890 ]
  notify:
    - stop kurento
    - reload systemd

- name: replace port
  become: true
  replace:
    path: "/usr/lib/systemd/system/kurento-media-server-{{ item }}.service"
    regexp: '%i'
    replace: '{{ item }}'
  loop: [ 8888, 8889, 8890 ]
  notify:
    - stop kurento
    - reload systemd

- name: add kurento-media-server.target
  become: true
  template:
    src: kurento-media-server.target
    dest: /usr/lib/systemd/system/kurento-media-server.target
    mode: 0644
  notify:
    - reload systemd

- name: remove kurento-media-server.service
  become: true
  file:
     path: /usr/lib/systemd/system/kurento-media-server.service
     state: absent

- name: prevent creation of transient systemd service for sysv service
  become: true
  file:
     path: /etc/init.d/kurento-media-server
     state: absent

- name: remove kurento-media-server.service override
  become: true
  file:
     path: /etc/systemd/system/kurento-media-server.service.d/override.conf
     state: absent

- name: deploy kurento service override configuration
  become: true
  template:
    src: kurento-mk.override
    dest: /etc/systemd/system/kurento-media-server.service
    force: true
  notify:
    - reload systemd

- meta: flush_handlers

- name: template kurento-media-server instance configs
  become: true
  template:
    src: "kurento.conf.json"
    dest: "/etc/kurento/kurento-{{ item }}.conf.json"
    mode: 0644
  loop: [ 8888, 8889, 8890 ]

- name: enable kurento-media-server instances
  become: true
  systemd:
     name: "kurento-media-server-{{ item }}"
     state: started
     enabled: yes
  loop: [ 8888, 8889, 8890 ]
  notify:
    - reload systemd
    - restart bigbluebutton

- name: increase kernel max PID number
  sysctl:
    name: kernel.pid_max
    value: 4194304
    sysctl_file: /etc/sysctl.d/20-kurento.conf
  notify:
    - restart kurento
