---
- name: Ensure nginx is started and enabled to start at boot.
  become: true
  systemd:
    name: nginx
    enabled: true
    state: started

- name: Create ssl folder for nginx
  become: true
  file:
    path: /etc/nginx/ssl
    mode: "0755"
    state: directory

- name: Copy predefined DH group ffdhe2048
  become: true
  copy:
    src: ffdhe4096.pem
    dest: /etc/nginx/ssl/ffdhe4096.pem
    mode: "0644"
  notify: Reload nginx

- name: Copy bbb's nginx vhost
  become: true
  template:
    src: nginx/vhost.conf
    dest: /etc/nginx/sites-available/bigbluebutton
    mode: "0644"
  notify: Reload nginx

- name: Remove nginx default config
  become: true
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: Reload nginx

- name: Ensure /etc/bigbluebutton/nginx folder exists
  become: true
  file:
    path: /etc/bigbluebutton/nginx
    owner: root
    group: root
    mode: "0755"
    state: directory

- name: Copy HTML5-Client-Log location snippet
  become: true
  copy:
    src: html5-client-log.nginx
    dest: /etc/bigbluebutton/nginx/html5-client-log.nginx
    mode: "0644"
  when: bbb_client_log_enable
  notify: Reload nginx

- name: Remove HTML5-Client-Log location snippet
  become: true
  file:
    path: /etc/bigbluebutton/nginx/html5-client-log.nginx
    state: absent
  when: not bbb_client_log_enable
  notify: Reload nginx

- name: Copy HTML5-Client-Log log-config snippet
  become: true
  copy:
    src: html5-client-log.conf
    dest: /etc/nginx/conf.d/html5-client-log.conf
    mode: "0644"
  when: bbb_client_log_enable
  notify: Reload nginx

- name: Remove HTML5-Client-Log location snippet
  become: true
  file:
    path: /etc/nginx/conf.d/html5-client-log.conf
    state: absent
  when: not bbb_client_log_enable
  notify: Reload nginx

- name: Create HTML5-Client-Log log-file
  become: true
  file:
    state: touch
    access_time: preserve
    modification_time: preserve
    path: /var/log/nginx/html5-client.log
    mode: "0640"
    owner: www-data
    group: adm
  when: bbb_client_log_enable
  notify: Reload nginx
